name: Deploy Marp Presentation
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build folder
        run: mkdir build

      - name: Marp Build (HTML)
        uses: KoharaKazuya/marp-cli-action@v4
        with:
          args: Diaporama.md -o build/index.html

      - name: Marp Build (PDF)
        uses: KoharaKazuya/marp-cli-action@v4
        with:
          args: Diaporama.md -o build/presentation.pdf

      - name: Deploy to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
