name: Deploy Marp Presentation
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Create build folder
        run: mkdir -p build

      - name: Compile ALL Marp Presentations (HTML & PDF)
        run: |
          marp --html --input-dir . --output build --ignore README.md
          marp --pdf --input-dir . --output build --ignore README.md

      - name: Copy README directly as index.html
        run: cp README.md build/index.html

      - name: Deploy to GitHub Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
